-- MySQL Script generated by MySQL Workbench
-- Thu Apr  4 19:44:58 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema easycomands
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema easycomands
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `easycomands` DEFAULT CHARACTER SET utf8 ;
USE `easycomands` ;

-- -----------------------------------------------------
-- Table `easycomands`.`setores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easycomands`.`setores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easycomands`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easycomands`.`categorias` (
  `id` TINYINT(3) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(10) NOT NULL,
  `setores_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_categoria_produtos_setores1_idx` (`setores_id` ASC),
  CONSTRAINT `fk_categoria_produtos_setores1`
    FOREIGN KEY (`setores_id`)
    REFERENCES `easycomands`.`setores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easycomands`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easycomands`.`produtos` (
  `id` TINYINT(3) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(20) NOT NULL,
  `categoria_produtos_id` TINYINT(3) NOT NULL,
  `preco` TINYINT(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_produtos_categoria_produtos_idx` (`categoria_produtos_id` ASC),
  CONSTRAINT `fk_produtos_categoria_produtos`
    FOREIGN KEY (`categoria_produtos_id`)
    REFERENCES `easycomands`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easycomands`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easycomands`.`pedidos` (
  `id` TINYINT(3) NOT NULL AUTO_INCREMENT,
  `mesa` INT(10) NOT NULL,
  `data` DATE NOT NULL,
  `hora` TIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easycomands`.`pedidos_has_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easycomands`.`pedidos_has_produtos` (
  `pedidos_id` TINYINT(3) NOT NULL,
  `produtos_id` TINYINT(3) NOT NULL,
  `quantidade` INT(10) NOT NULL,
  `status` TINYINT(3) NOT NULL,
  PRIMARY KEY (`pedidos_id`, `produtos_id`),
  INDEX `fk_pedidos_has_produtos_produtos1_idx` (`produtos_id` ASC),
  INDEX `fk_pedidos_has_produtos_pedidos1_idx` (`pedidos_id` ASC),
  CONSTRAINT `fk_pedidos_has_produtos_pedidos1`
    FOREIGN KEY (`pedidos_id`)
    REFERENCES `easycomands`.`pedidos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_has_produtos_produtos1`
    FOREIGN KEY (`produtos_id`)
    REFERENCES `easycomands`.`produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easycomands`.`administradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easycomands`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `nivel_de_permissao` INT NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `setores_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_funcionarios_setores1_idx` (`setores_id` ASC),
  CONSTRAINT `fk_funcionarios_setores1`
    FOREIGN KEY (`setores_id`)
    REFERENCES `easycomands`.`setores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
